# Generated by Django 3.2.11 on 2022-01-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playCheseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=6)),
            ],
        ),
    ]
